= Mentor Documentation
Martin Penckert <martin.penckert@gmail.com>
Version 0.0.1, 2020-06-24


== Domain

Business domain is a German mental health and support system. Therefore most business terms are kept in German, e.g. `Angebot` or `Qualitaetskriterium`. 
Documentation is kept in English for purpose of foreign inclusion. Every German term is anotated by a comment explaining its meaning and intent.

== Code Style

Please read the Elixir code guidelines (https://github.com/christopheradams/elixir_style_guide).

== Diagnose (Questionnaire)
The questionnaire (domain term: `Diagnose`) is the central user facing part of the application.
It is essentially a multi-part-form diagnostic that results either in general help and informations about mental health or in a specific list of `-> Angebot`.

=== Survey
Opening the questionnaire that is composed of questions and answers will create a `Survey`. This can be seen as an instance of the Questionnaire. It holds all the choices (`-> Choice`) the user makes while going through the diagnostic questionnaire. The user should not have to create an account or login to one to use the diagnostic service. So we provide a `survey_id` that tracks the survey. It is generated uniquely and randomly when the survey is started. The `survey_id` can be copied and saved by the user to come back to the survey later and finish it, if it's unfinished yet or revisit the results if the suvey has been finished.

=== Question
A `Question` is one central data point - or: _step_ - in the survey. Questions are stored in the database. A question has both a `predecessor` and `successor` that are the questions coming before and after this one. For the first question `predecessor` is `nil`. For the last question `successor` is `nil`. A question also has a list of answers (`-> Answer`). Questions might also be `multiple_choice`.

=== Answer
An `Answer` is subdata to a `-> Question`. It belongs to one question and has a `order_number` that defines the order in which the answers appear beneath the question; the number is mutable.

=== Choice
A `Choice` holds a single answer to a question the user has chosen. It also is bound to a survey to. If the user answers a question a choice is generated, each for every answer the user has activated for that question. If the user does come back to a question and changes the answers all choices are delted and generated newly.

== Backend

=== Angebot

`Angebot` (service offering) discribes the central data unit. A `Angebot` is essentially the resulting document of a `-> Diagnose`.

.Angebot
[source, elixir]
----
# main information
titel                # string          - (unique) title
beschreibung         # string          - short description of the service offered
link                 # string          - hyperlink to the service's website
typ                  # list of strings - Prävention | Hilfsangebot | Information
qualitaetskriterium  # string          - Kammer | KV - Who has verified the service?

# Boolean values defining the kind of service
einzelangebot                 # boolean - ??
suchfunktion                  # boolean - ??
psycho_therapie_vermittlung   # boolean - does the service provide transfer to therapy
beratungsangebot              # boolean - ??
hotline                       # boolean - does the service provide a phone hotline

# service formats available
app        # boolean - has it an mobile App?
website    # boolean - has it a website?
pdf_file   # boolean - has it a pdf file?
video      # boolean - has it a video?

# further service formats
selbsthilfegruppe   # boolean - provides encounter group
forum               # boolean - provides professionally guided online boards
chatbot             # boolean - provides chat (-bot)
selbsttest          # boolean - provides self evaluation survey
psychoedukation     # boolean - provides further educational information to mental health issues
corona              # boolean - provides COVID-19 specific information or services

# language patterns
alternative_sprachen          # list of strings - languages supported (besides German), e.g. English, Arabic, sign language
einfache_sprache              # boolean         - language is kept simple, w/o technical vocabulary
entstigmatisierende_sprache   # boolean         - ??
genderneutrale_sprache        # boolean         - languages addresses all gender indetification
ansprache                     # string - Du | Sie | unpersönlich - formal or informal saluation

# more criteria
ansprechendes_design   # boolean - modern, friendly design

# diagnostic focus
transdiagnostisch      # boolean         - Service not specialized towards one issue
beschwerdespezifisch   # list of strings - Service is specialiced towards one issue
zielgruppen            # list of strings - target groups

# area of service
region       # string          - national | regional | beides - area delimiter
bundesland   # list of strings - optional state of regional service
city         # string          - optional specification of city of regional service

# sponsorship
organisation    # string  - organisation responsible for the service
konfessionell   # boolean - sectarian organisaion?
kosten          # string  - kostenlos | erstattet | kostenpflichtig | teilweise kostenpflichtig
                #         - cost of service

# research (internal data)
anmerkungen            # string - notes of the researcher in charge
recherchiert_von       # string - name of researcher
geprueft_von           # string - name of auditor
aufnahmevorschlag      # boolean - should be in the system?
aufnahmeentscheidung   # boolean - is in the system?

# more
screening    # boolean - the researcher has gone deeper than just a first screening
mm_favorit   # boolean - is a favourite service of the mental mentor team
----

== Operations

=== Local Dev

To start your Phoenix server:

  * Install dependencies with `mix deps.get`
  * Create and migrate your database with `mix ecto.setup`
  * Install Node.js dependencies with `npm install` inside the `assets` directory
  * Start Phoenix endpoint with `mix phx.server`

Now you can visit [`localhost:4000`](http://localhost:4000) from your browser.

Ready to run in production? Please [check our deployment guides](https://hexdocs.pm/phoenix/deployment.html).

==== Learn more

  * Official website: https://www.phoenixframework.org/
  * Guides: https://hexdocs.pm/phoenix/overview.html
  * Docs: https://hexdocs.pm/phoenix
  * Forum: https://elixirforum.com/c/phoenix-forum
  * Source: https://github.com/phoenixframework/phoenix


=== Heroku (Execution Environment)
The application is currently hosted on Heroku to provide a quick feedback loop (easy to setup and bring into CI with GitHub).
The address is `https://mental-mentor.herokuapp.com/`. +

I followed this tutorial to get it up and running: https://hexdocs.pm/phoenix/heroku.html. +

Afterthought: Maybe it would be a good idea using a Docker container with Heroku here.

=== PostgreSQL (Database)
I used a PostgreSQL database - both, locally as well as with Heroku - just for the sake of being very familiar with it. At Heroku this is currently a `hobby-dev`-tier database for it is free of charge.

